close all;
noisymri = readDoubleImage('noisymri');
[a, h, v, d] = dwt2(noisymri, 'haar');
threshold = 25;
mode = 's';
a = wthresh(a, mode, threshold);
h = wthresh(h, mode, threshold);
v = wthresh(v, mode, threshold);
d = wthresh(d, mode, threshold);
imshow(noisymri, [0 255]); figure;
imshow(idwt2(a, h, v, d, 'haar'), [0 255]);
